name: Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0']

        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
            # report phpunit errors into files-changed PR tab
            # https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
            -   name: Setup Problem Matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   if: matrix.php == '8.0'
                # because php-cs-fixer prevents 8.0 in composer.json in dev, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5134
                run: composer install --no-progress --ansi --ignore-platform-reqs

            -   if: matrix.php != '8.0'
                run: composer install --no-progress --ansi

            -   run: vendor/bin/phpunit
